FROM node:latest AS node_stage
# Here we copy data over from the current /app/ directory to the docker instance 
# then we run the bash shell/app
WORKDIR /app
COPY ./NodeJS_CLI/package.json /app/
COPY ./NodeJS_CLI/package-lock.json /app/
RUN npm install
COPY ./NodeJS_CLI /app/
COPY NodeJS_CLI/cli-app.sh /app/cli-app.sh
# RUN chmod +x /app/cli-app.sh
# CMD ["/app/cli-app.sh"]